window.locations = {
  common: [
    "California",
    "Florida",
    "Georgia",
    "Illinois",
    "Michigan",
    "Nevada",
    "New Jersey",
    "New York",
    "Texas",
    "Ontario",
  ],
  rare: [
    "Alabama",
    "Arizona",
    "Arkansas",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Idaho",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "New Hampshire",
    "New Mexico",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Alberta",
    "British Columbia",
    "Manitoba",
    "Quebec",
    "Foreign country",
  ],
  legendary: [
    "Alaska",
    "District of Columbia",
    "Hawaii",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Prince Edward Island",
    "Saskatchewan",
  ]
};
